import { existsSync, readFileSync } from "node:fs"
import path from "node:path"
import { expect, test } from "@playwright/test"

const readFrontSource = (relativePath: string) =>
  readFileSync(path.resolve(__dirname, "../src", relativePath), "utf8")

test.describe("관리자 런타임 회귀 계약", () => {
  test("운영 브라우저 API는 로그인과 관리자 요청, 알림 snapshot, 작성 temp draft를 same-origin 백엔드 프록시로 보낸다", () => {
    const clientSource = readFrontSource("apis/backend/client.ts")
    const notificationsSource = readFrontSource("apis/backend/notifications.ts")
    const editorRootModelSource = readFrontSource("routes/Admin/EditorStudioWorkspaceControllerRootModel.ts")
    const proxySourcePath = path.resolve(__dirname, "../src/pages/api/backend/[...path].ts")

    expect(clientSource).toContain('const BROWSER_BACKEND_PROXY_PREFIX = "/api/backend"')
    expect(clientSource).toContain("const shouldUseBrowserBackendProxy = (safePath: string) =>")
    expect(clientSource).toContain('process.env.NODE_ENV === "production"')
    expect(clientSource).toContain("safePath.startsWith(\"/member/api/v1/auth/\")")
    expect(clientSource).toContain("safePath.startsWith(\"/member/api/v1/notifications/snapshot\")")
    expect(clientSource).toContain("safePath.startsWith(\"/post/api/v1/posts/temp\")")
    expect(clientSource).toContain("safePath.startsWith(\"/system/api/v1/adm/\")")
    expect(clientSource).toContain("return `${BROWSER_BACKEND_PROXY_PREFIX}${safePath}`")
    expect(notificationsSource).toContain("return new URL(NOTIFICATIONS_STREAM_API_PATH, `${apiBaseUrl}/`).toString()")
    expect(editorRootModelSource).toContain('import { getApiRequestUrl } from "src/apis/backend/client"')
    expect(editorRootModelSource).toContain('fetch(getApiRequestUrl("/post/api/v1/posts/temp"), {')
    expect(editorRootModelSource).toContain('"X-Aquila-CSRF": "1"')
    expect(editorRootModelSource).not.toContain('fetch(`${getApiBaseUrl()}/post/api/v1/posts/temp`, {')

    expect(existsSync(proxySourcePath)).toBe(true)
    const proxySource = readFileSync(proxySourcePath, "utf8")
    expect(proxySource).toContain("bodyParser: false")
    expect(proxySource).toContain("normalizeApiRequestPath")
    expect(proxySource).toContain("resolveServerApiBaseUrl")
    expect(proxySource).not.toContain('import { Readable } from "node:stream"')
    expect(proxySource).toContain("const isAbortLikeError = (error: unknown) =>")
    expect(proxySource).toContain("signal: AbortSignal")
    expect(proxySource).toContain("const toArrayBuffer = (buffer: Buffer): ArrayBuffer")
    expect(proxySource).toContain("new Promise<BodyInit>")
    expect(proxySource).toContain('req.on("data", handleData)')
    expect(proxySource).toContain("Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)")
    expect(proxySource).toContain("const DEFAULT_BACKEND_PROXY_MAX_BODY_BYTES = 50 * 1024 * 1024")
    expect(proxySource).toContain('process.env.BACKEND_PROXY_MAX_BODY_BYTES')
    expect(proxySource).toContain('firstHeaderValue(req.headers["content-length"])')
    expect(proxySource).toContain("throw new ProxyBodyTooLargeError()")
    expect(proxySource).toContain("throw new ProxyBodyTimeoutError()")
    expect(proxySource).toContain("signal.addEventListener(\"abort\", handleAbort, { once: true })")
    expect(proxySource).toContain("if (signal.aborted)")
    expect(proxySource).toContain("req.pause()")
    expect(proxySource).not.toContain("req.destroy(")
    expect(proxySource).toContain("resolve(toArrayBuffer(Buffer.concat(chunks)))")
    expect(proxySource).not.toContain("req as unknown as BodyInit")
    expect(proxySource).toContain('headers.set("X-Forwarded-Host"')
    expect(proxySource).toContain('headers.set("X-Forwarded-Proto", firstHeaderValue(req.headers["x-forwarded-proto"]) || "https")')
    expect(proxySource).toContain('headers.set("X-Forwarded-For", clientIp)')
    expect(proxySource).toContain("const BACKEND_PROXY_TIMEOUT_MS = 120_000")
    expect(proxySource).toContain("const controller = new AbortController()")
    expect(proxySource).toContain("const timeoutId = setTimeout(() => controller.abort(), BACKEND_PROXY_TIMEOUT_MS)")
    expect(proxySource).toContain("signal: controller.signal")
    expect(proxySource).toContain("clearTimeout(timeoutId)")
    expect(proxySource).toContain("res.status(413).json")
    expect(proxySource).toContain("controller.signal.aborted || isAbortLikeError(error)")
    expect(proxySource).toContain("res.status(504).json")
    expect(proxySource).not.toContain('duplex: "half"')
    expect(proxySource).toContain('normalizedKey === "host"')
    expect(proxySource).toContain('normalizedKey === "accept-encoding"')
    expect(proxySource).toContain('const DECODED_RESPONSE_HEADERS = new Set(["content-encoding", "content-length"])')
    expect(proxySource).toContain("DECODED_RESPONSE_HEADERS.has(normalizedKey)")
  })

  test("클라우드 목록과 업로드는 프록시 가능한 URL 생성기를 공유한다", () => {
    const cloudSource = readFrontSource("apis/backend/cloud.ts")

    expect(cloudSource).toContain('import { apiFetch, getApiRequestUrl } from "./client"')
    expect(cloudSource).toContain("getApiRequestUrl(`/system/api/v1/adm/cloud/files/${fileId}/content`)")
    expect(cloudSource).not.toContain("getApiBaseUrl")
  })

  test("프로필 이미지 업로드는 CSRF preflight 헤더를 포함한다", () => {
    const profilePersistenceSource = readFrontSource("routes/Admin/AdminProfilePersistenceModel.ts")
    const legacyProfileSource = readFrontSource("routes/Admin/useEditorStudioProfileCommands.ts")

    expect(profilePersistenceSource).toContain('"X-Aquila-CSRF": "1"')
    expect(legacyProfileSource).toContain("PROFILE_IMAGE_CSRF_PREFLIGHT_HEADERS")
  })

  test("프로필 이미지 편집 모달은 과거 이미지 선택과 삭제 동선을 제공한다", () => {
    const modalSource = readFrontSource("routes/Admin/AdminProfileImageEditorModal.tsx")
    const sectionSource = readFrontSource("routes/Admin/AdminProfileWorkspaceSections.tsx")
    const pageModelSource = readFrontSource("routes/Admin/AdminProfileWorkspacePageModel.ts")

    expect(modalSource).toContain("previousProfileImages")
    expect(modalSource).toContain("onSelectPreviousProfileImage")
    expect(modalSource).toContain("onDeletePreviousProfileImage")
    expect(sectionSource).toContain("previousProfileImages={previousProfileImages}")
    expect(pageModelSource).toContain("previousProfileImages")
  })

  test("새로고침 전 첫 페인트는 저장된 테마나 시스템 다크 모드를 먼저 적용한다", () => {
    const documentSource = readFrontSource("pages/_document.tsx")
    const schemeSource = readFrontSource("hooks/useScheme.ts")
    const adminColorTokenSource = readFrontSource("routes/Admin/adminColorTokens.ts")

    expect(documentSource).toContain("AQUILA_SCHEME_BOOTSTRAP_SCRIPT")
    expect(documentSource).toContain("AQUILA_CONFIGURED_SCHEME")
    expect(documentSource).toContain('var configuredScheme = "${AQUILA_CONFIGURED_SCHEME}"')
    expect(documentSource).toContain('var defaultScheme = configuredScheme === "system"')
    expect(documentSource).toContain('var bootstrapSource = cachedScheme ? "cookie" : "system"')
    expect(documentSource).toContain('document.documentElement.dataset.aquilaScheme = nextScheme')
    expect(documentSource).toContain('document.documentElement.setAttribute("data-aquila-scheme-config", configuredScheme)')
    expect(documentSource).toContain('document.documentElement.setAttribute("data-aquila-scheme-bootstrap", nextScheme)')
    expect(documentSource).toContain('document.documentElement.setAttribute("data-aquila-scheme-bootstrap-source", bootstrapSource)')
    expect(documentSource).toContain("prefers-color-scheme: dark")
    expect(documentSource).toContain("colorScheme = nextScheme")
    expect(documentSource).toContain('nextScheme === "dark" ? "#0d1117" : "#f3f5f8"')
    expect(documentSource).toContain('var darkPreHydrationGuard = nextScheme === "dark"')
    expect(documentSource).toContain('html[data-aquila-scheme-bootstrap="dark"] *{color-scheme:dark!important;}')
    expect(documentSource).toContain('background-color:transparent!important;background-image:none!important;box-shadow:none!important;')
    expect(documentSource).toContain('[role="search"],[class*="Card"],[class*="card"]')
    expect(documentSource).toContain('" + darkPreHydrationGuard')
    expect(documentSource).not.toContain("#111318")
    expect(documentSource).toContain("html[data-aquila-scheme-bootstrap] body")
    expect(schemeSource).toContain("initialData: fallbackScheme")
    expect(schemeSource).toContain('setCookie("scheme", scheme, { path: "/", sameSite: "lax" })')
    expect(schemeSource).toContain("resolveCachedScheme() ?? defaultScheme")
    expect(schemeSource).not.toContain("resolveInitialBrowserScheme")
    expect(schemeSource).toContain("clearSchemeBootstrapAfterHydration")
    expect(schemeSource).toContain('style[data-aquila-scheme-bootstrap-style="true"]')
    expect(schemeSource).toContain('window.matchMedia?.("(prefers-color-scheme: dark)")?.matches')
    expect(adminColorTokenSource).toContain('html[data-aquila-scheme-bootstrap-source="cookie"][data-aquila-scheme-bootstrap="dark"] &')
    expect(adminColorTokenSource).toContain('html[data-aquila-scheme-bootstrap-source="system"][data-aquila-scheme-bootstrap="dark"] &')
    expect(adminColorTokenSource).toContain('html[data-aquila-scheme-bootstrap-source="cookie"][data-aquila-scheme-bootstrap="light"] &')
    expect(adminColorTokenSource).toContain('html[data-aquila-scheme-bootstrap-source="system"][data-aquila-scheme-bootstrap="light"] &')
  })
})

test.describe("공개 피드 접근성 회귀 계약", () => {
  test("홈 피드 활성 태그는 밝은 배경에서 충분한 대비의 텍스트 색을 사용한다", () => {
    const tagListSource = readFrontSource("routes/Feed/TagList.tsx")

    expect(tagListSource).toContain("--feed-tag-accent-text")
    expect(tagListSource).toContain('theme.scheme === "light" ? theme.colors.blue11 : theme.colors.blue10')
    expect(tagListSource).toContain("color: var(--feed-tag-accent-text);")
  })
})
