import { readFileSync } from "node:fs"
import path from "node:path"
import { expect, test } from "@playwright/test"

test.describe("admin posts workspace link contract", () => {
  test("posts workspace uses detail-like hero copy and checklist rail labels", () => {
    const source = readFileSync(path.resolve(__dirname, "../src/routes/Admin/AdminPostsWorkspacePage.tsx"), "utf8")
    const pageViewSource = readFileSync(path.resolve(__dirname, "../src/routes/Admin/AdminPostsWorkspacePageView.tsx"), "utf8")
    const recentWorkSource = readFileSync(
      path.resolve(__dirname, "../src/routes/Admin/AdminPostsWorkspaceRecentWork.tsx"),
      "utf8"
    )

    expect(pageViewSource).toContain("<h1>글 관리</h1>")
    expect(source).not.toContain("최근 초안 복귀, 공개 상태 점검, 목록 필터링까지 지금 필요한 글 작업 흐름을 한곳에 모읍니다.")
    expect(source).not.toContain("<h2>검수 체크리스트</h2>")
    expect(source).not.toContain("<h2>상태 의미</h2>")
    expect(source).not.toContain("<h2>바로가기</h2>")
    expect(source).not.toContain("const WorkspaceRail = styled(AdminStickyRail)`")
    expect(recentWorkSource).toContain("grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr));")
  })

  test("관리자 글 목록은 V4 table row editor 진입 계약을 유지한다", () => {
    const listSource = readFileSync(path.resolve(__dirname, "../src/routes/Admin/AdminPostsWorkspaceList.tsx"), "utf8")
    const listStyleSource = readFileSync(path.resolve(__dirname, "../src/routes/Admin/AdminPostsWorkspaceList.styles.ts"), "utf8")
    const modelSource = readFileSync(path.resolve(__dirname, "../src/routes/Admin/AdminPostsWorkspaceModel.ts"), "utf8")
    const pageSource = readFileSync(path.resolve(__dirname, "../src/routes/Admin/AdminPostsWorkspacePage.tsx"), "utf8")
    const pageViewSource = readFileSync(path.resolve(__dirname, "../src/routes/Admin/AdminPostsWorkspacePageView.tsx"), "utf8")
    const recentWorkSource = readFileSync(
      path.resolve(__dirname, "../src/routes/Admin/AdminPostsWorkspaceRecentWork.tsx"),
      "utf8"
    )

    expect(modelSource).toContain('if (visibility === "PUBLIC_UNLISTED") return "링크 공개"')
    expect(listSource).toContain('from "./AdminPostsWorkspaceList.styles"')
    expect(listStyleSource).toContain("AdminInlineActionRow,")
    expect(listStyleSource).toContain("AdminStatusPill,")
    expect(listStyleSource).toContain("AdminTextActionButton,")
    expect(listSource).toContain('<th className="selectCell"></th>')
    expect(listSource).toContain("<th>Title</th>")
    expect(listSource).toContain('<th className="topicCell">Topic</th>')
    expect(listSource).toContain('<th className="statusCell">Status</th>')
    expect(listSource).toContain('<th className="dateCell">Updated</th>')
    expect(listSource).toContain('<th className="viewsCell">{isDeletedScope ? "Actions" : "Views"}</th>')
    expect(listSource).toContain("const openEditorForRow = (row: AdminPostListItem) => onOpenWriteRoute({ postId: String(row.id) })")
    expect(listSource).toContain("<TitleButton type=\"button\" onClick={() => openEditorForRow(row)}>")
    expect(listSource).not.toContain('role={isDeletedScope ? undefined : "button"}')
    expect(listSource).toContain("onRestorePost(row)")
    expect(listSource).toContain("onHardDeletePost(row)")
    expect(listSource).toContain("onDeletePost(row)")
    expect(listSource).toContain("onClick={() => onPageChange(currentPage + 1)}")
    expect(listStyleSource).toContain("export const PageFooter = styled(ActionRow)`")
    expect(listStyleSource).toContain("export const TitleButton = styled.button`")
    expect(pageSource).toContain("listPage={listPage}")
    expect(pageSource).toContain("status: listStatus")
    expect(pageSource).not.toContain("for (let pageNumber")
    expect(pageSource).not.toContain("const displayListState = useMemo")
    expect(modelSource).toContain("if (isServerTempDraftPost(row)) return \"draft\"")
    expect(modelSource).toContain('query.set("status", options.status)')
    expect(listSource).toContain("<TitleButton type=\"button\" onClick={() => openEditorForRow(row)}>")
    expect(listSource).toContain('const getStatusLabel = (row: AdminPostListItem) => (listScope === "deleted" ? "삭제됨" : workspaceStatusLabel(row))')
    expect(listSource).toContain('const getStatusTone = (row: AdminPostListItem) => (listScope === "deleted" ? "PRIVATE" : toVisibility(row.published, row.listed))')
    expect(listSource).toContain('<span className="dateCell">Updated</span>')
    expect(listSource).toContain('<div className="cell viewsCell">')
    expect(listSource).toContain('<div className="metaRow">')
    expect(listSource).toContain("getWorkspaceTopicLabel(row)")
    expect(listSource).toContain("formatWorkspaceViews(row)")
    expect(modelSource).toContain('category?: string | string[]')
    expect(modelSource).toContain('tags?: string[]')
    expect(listSource).not.toContain('<div className="titleRow">')
    expect(listSource).not.toContain("TitleAnchor")
    expect(listSource).not.toContain("상세 열기")
    expect(listSource).not.toContain("링크 복사")
    expect(recentWorkSource).toContain("recentPosts.slice(0, 3)")
    expect(recentWorkSource).toContain("grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr));")
    expect(pageViewSource).toContain("<h1>글 관리</h1>")
    expect(recentWorkSource).toContain('<ResumeCardButton type="button" onClick={() => onOpenWriteRoute({ source: "local-draft" })}>')
    expect(recentWorkSource).toContain("const ResumeCardButton = styled.button`")
    expect(recentWorkSource).not.toContain('<PrimaryInlineButton type="button" onClick={() => onOpenWriteRoute({ source: "local-draft" })}>')
    expect(recentWorkSource).not.toContain('data-emphasis={localDraft ? "strong" : "soft"}')
    expect(recentWorkSource).not.toContain('data-clickable={localDraft ? "true" : undefined}')
  })

  test("브라우저 임시저장 카드는 본문 markdown preview를 직접 노출하지 않는다", () => {
    const source = readFileSync(path.resolve(__dirname, "../src/routes/Admin/AdminPostsWorkspaceRecentWork.tsx"), "utf8")

    expect(source).not.toContain("summary: summary || content.slice(0, 120)")
    expect(source).not.toContain("{localDraft.summary ? <ResumeDescription>{localDraft.summary}</ResumeDescription> : null}")
    expect(source).toContain("{localDraft.savedAt ? <span>{formatDateTime(localDraft.savedAt)}</span> : null}")
    expect(source).toContain("<ResumeTitle>{localDraft.title}</ResumeTitle>")
  })

  test("글 관리 API 실패 문구는 raw fetch detail을 사용자-facing 상태에 직접 노출하지 않는다", () => {
    const source = readFileSync(path.resolve(__dirname, "../src/routes/Admin/AdminPostsWorkspacePage.tsx"), "utf8")

    expect(source).toContain("POSTS_LIST_LOAD_ERROR_MESSAGE")
    expect(source).toContain("RECENT_POSTS_UNAVAILABLE_MESSAGE")
    expect(source).not.toContain("글 목록을 불러오지 못했습니다: ${message}")
    expect(source).not.toContain("최근 글을 불러오지 못했습니다: ${message}")
  })

  test("관리자 작성 화면은 V4 editor head에서 canonical 링크 액션을 노출하지 않는다", () => {
    const source = readFileSync(
      path.resolve(__dirname, "../src/routes/Admin/EditorStudioWorkspaceControllerRootView.tsx"),
      "utf8"
    )
    const editorSurfaceSource = readFileSync(
      path.resolve(__dirname, "../src/routes/Admin/EditorStudioDedicatedEditorSurface.tsx"),
      "utf8"
    )

    expect(source).toContain("onOpenPostDetail={(id) => void openPostDetailRoute(id)}")
    expect(source).toContain("onCopyPostDetailLink={(id, title) => void copyPostDetailLink(id, title)}")
    expect(editorSurfaceSource).toContain("본문 형식 · Markdown")
    expect(editorSurfaceSource).not.toContain("onOpenPostDetail")
    expect(editorSurfaceSource).not.toContain("onCopyPostDetailLink")
    expect(editorSurfaceSource).not.toContain("상세 열기")
    expect(editorSurfaceSource).not.toContain("링크 복사")
  })

  test("V4 markdown editor는 code title snippet과 모바일 split preview를 유지한다", () => {
    const source = readFileSync(path.resolve(__dirname, "../src/components/markdown-editor/MarkdownEditor.tsx"), "utf8")
    const editorNewPageSource = readFileSync(path.resolve(__dirname, "../src/pages/editor/new.tsx"), "utf8")
    const editorPostPageSource = readFileSync(path.resolve(__dirname, "../src/pages/editor/[id].tsx"), "utf8")
    const legacyWriteRedirectSource = readFileSync(path.resolve(__dirname, "../src/pages/admin/posts/write.tsx"), "utf8")
    const controllerRootSource = readFileSync(
      path.resolve(__dirname, "../src/routes/Admin/EditorStudioWorkspaceControllerRoot.tsx"),
      "utf8"
    )
    const guideSource = readFileSync(
      path.resolve(__dirname, "../src/routes/Admin/EditorStudioDedicatedEditorSurface.tsx"),
      "utf8"
    )
    const editorPartsSource = readFileSync(
      path.resolve(__dirname, "../src/routes/Admin/EditorStudioDedicatedEditorSurfaceParts.tsx"),
      "utf8"
    )
    const controllerSource = readFileSync(
      path.resolve(__dirname, "../src/routes/Admin/EditorStudioWorkspaceControllerRootView.tsx"),
      "utf8"
    )
    const editorRootStyle = editorPartsSource.match(/export const EditorStudioRoot[\s\S]*?`;/)?.[0] ?? ""
    const editorFrameStyle = editorPartsSource.match(/export const EditorStudioFrame[\s\S]*?`;/)?.[0] ?? ""
    const editorWritingColumnStyle =
      editorPartsSource.match(/export const EditorStudioWritingColumn[\s\S]*?`;/)?.[0] ?? ""
    const editorCanvasSectionStyle =
      editorPartsSource.match(/export const EditorStudioDedicatedCanvasSection[\s\S]*?`;/)?.[0] ?? ""
    const publishNoticeStyle = editorPartsSource.match(/export const PublishNotice[\s\S]*?`;/)?.[0] ?? ""
    const editorTagRowStyle = editorPartsSource.match(/export const EditorTagRow[\s\S]*?`;/)?.[0] ?? ""
    const selectedTagChipStyle = editorPartsSource.match(/export const SelectedTagChip[\s\S]*?`;/)?.[0] ?? ""
    const editorHeaderMetaRowStyle = editorPartsSource.match(/export const EditorHeaderMetaRow[\s\S]*?`;/)?.[0] ?? ""
    const editorMetaSectionStyle =
      editorPartsSource.match(/export const EditorStudioDedicatedMetaSection[\s\S]*?`;/)?.[0] ?? ""
    const titleInputStyle = editorPartsSource.match(/export const TitleInput[\s\S]*?`;/)?.[0] ?? ""
    const editorInspectorStyle = editorPartsSource.match(/export const EditorInspector = styled\.aside`[\s\S]*?`;/)?.[0] ?? ""
    const inspectorTagInputRowStyle =
      editorPartsSource.match(/export const EditorInspectorTagInputRow[\s\S]*?`;/)?.[0] ?? ""
    const inspectorFullWidthActionStyle =
      editorPartsSource.match(/export const EditorInspectorFullWidthAction[\s\S]*?`;/)?.[0] ?? ""
    const markdownEditorRootStyle = source.match(/const EditorRoot = styled\.section`[\s\S]*?\n`/)?.[0] ?? ""
    const markdownEditorToolbarStyle = source.match(/const EditorToolbar = styled\.div`[\s\S]*?\n`/)?.[0] ?? ""
    const markdownToolbarGroupStyle = source.match(/const ToolbarGroup = styled\.div`[\s\S]*?\n`/)?.[0] ?? ""
    const markdownEditorBodyStyle = source.match(/const EditorBody = styled\.div`[\s\S]*?\n`/)?.[0] ?? ""
    const markdownWritePaneStyle = source.match(/const WritePane = styled\.div`[\s\S]*?\n`/)?.[0] ?? ""
    const markdownTextareaStyle = source.match(/const MarkdownTextarea = styled\.textarea`[\s\S]*?\n`/)?.[0] ?? ""
    const markdownPreviewPaneStyle = source.match(/const PreviewPane = styled\.div`[\s\S]*?\n`/)?.[0] ?? ""
    const markdownPreviewArticleStyle = source.match(/const PreviewArticle = styled\.article`[\s\S]*?\n`/)?.[0] ?? ""

    expect(editorNewPageSource).toContain("getEditorStudioPageProps")
    expect(editorPostPageSource).toContain("getEditorStudioPageProps")
    expect(legacyWriteRedirectSource).toContain('destination: "/editor/new"')
    expect(legacyWriteRedirectSource).toContain("destination: `/editor/${encodeURIComponent(postId)}`")
    expect(controllerRootSource).toContain('const isDedicatedEditorRoute = router.pathname.startsWith("/editor")')
    expect(controllerSource).toContain("if (isDedicatedEditorRoute) {")
    expect(controllerSource).toContain("<EditorStudioDedicatedEditorSurface")
    expect(controllerSource).toContain("editorCanvas={dedicatedEditorCanvas}")
    expect(source).toContain('```kotlin title="invalidatePost.kt"')
    expect(source).toContain("| 항목 | 설명 |")
    expect(source).not.toContain("| Column 1 | Column 2 | Column 3 |")
    expect(source).toContain("title={snippet.title}")
    expect(source).toContain('<ImageUploadButton title="이미지" aria-label="이미지" aria-disabled={disabled || !onUploadImage}>')
    expect(source).toContain("previewTitle?: string")
    expect(source).toContain("previewSummary?: string")
    expect(source).toContain("<PreviewHeader>")
    expect(source).toContain("{previewTitle ? <h1>{previewTitle}</h1> : null}")
    expect(source).toContain("{previewSummary ? <p>{previewSummary}</p> : null}")
    expect(source).not.toContain("<h1>캐시가 빨라질수록")
    expect(source).toContain("padding: 48px 44px 110px;")
    expect(source).toContain("@media (max-width: 820px)")
    expect(source).toContain("@media (max-width: 1100px)")
    expect(source).not.toContain("@media (max-width: 980px)")
    expect(source).toContain('&[data-mode="split"] [data-pane="preview"]')
    expect(source).toContain("ref={previewScrollRef}")
    expect(source).toContain("onScroll={handlePreviewScroll}")
    expect(source).toContain("onWheel={handlePreviewWheel}")
    expect(markdownEditorRootStyle).toContain("box-sizing: border-box;")
    expect(markdownEditorRootStyle).toContain("width: 100%;")
    expect(markdownEditorRootStyle).toContain("max-width: 100%;")
    expect(markdownEditorRootStyle).toContain("min-width: 0;")
    expect(markdownEditorToolbarStyle).toContain("box-sizing: border-box;")
    expect(markdownEditorToolbarStyle).toContain("width: 100%;")
    expect(markdownEditorToolbarStyle).toContain("max-width: 100%;")
    expect(markdownEditorToolbarStyle).toContain("min-width: 0;")
    expect(markdownToolbarGroupStyle).toContain("min-width: 0;")
    expect(markdownToolbarGroupStyle).toContain("max-width: 100%;")
    expect(markdownToolbarGroupStyle).toContain("overflow-x: auto;")
    expect(markdownEditorBodyStyle).toContain("min-height: 0;")
    expect(markdownEditorBodyStyle).toContain("min-width: 0;")
    expect(markdownEditorBodyStyle).toContain("max-width: 100%;")
    expect(markdownEditorBodyStyle).toContain("grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);")
    expect(markdownEditorBodyStyle).toContain("theme.publicDesign.readableSurface")
    expect(markdownEditorBodyStyle).toContain('max-width: 820px;')
    expect(markdownEditorBodyStyle).toContain("height: 46vh;")
    expect(markdownEditorBodyStyle).toContain("border-right: 0;")
    expect(markdownEditorBodyStyle).toContain("border-bottom: 1px solid")
    expect(markdownWritePaneStyle).toContain("min-height: 0;")
    expect(markdownWritePaneStyle).toContain("overflow: auto;")
    expect(markdownTextareaStyle).toContain("height: 100%;")
    expect(markdownTextareaStyle).toContain("min-height: 640px;")
    expect(markdownTextareaStyle).toContain("padding: 30px 32px;")
    expect(markdownTextareaStyle).toContain("resize: none;")
    expect(markdownPreviewPaneStyle).toContain("min-height: 0;")
    expect(markdownPreviewPaneStyle).toContain("overflow-y: auto;")
    expect(markdownPreviewPaneStyle).toContain("overscroll-behavior: contain;")
    expect(markdownPreviewArticleStyle).toContain("max-width: 760px;")
    expect(markdownPreviewArticleStyle).toContain("margin: 0 auto;")
    expect(controllerSource).toContain("previewTitle={postTitle}")
    expect(controllerSource).toContain("previewSummary={resolvedPreviewSummary}")
    expect(controllerSource).not.toContain("캐시가 빨라질수록")
    expect(controllerSource).not.toContain("ETag, Redis, CDN")
    expect(controllerSource).toContain("postTags={postTags}")
    expect(controllerSource).toContain("postTitle={postTitle}")
    expect(controllerSource).toContain("postSummary={postSummary}")
    expect(controllerSource).toContain("postVisibility={postVisibility}")
    expect(controllerSource).toContain("onPostSummaryChange={setPostSummary}")
    expect(controllerSource).toContain("onPostVisibilityChange={setPostVisibility}")
    expect(controllerSource).not.toContain("handleRecommend")
    expect(controllerSource).not.toContain('loadingKey === "recommend')
    expect(guideSource).toContain("postTags : postTitle.trim().split")
    expect(guideSource).toContain("<div>{thumbnailPreviewLabel}</div>")
    expect(guideSource).not.toContain('|| "DRAFT"')
    expect(guideSource).toContain("value={postTitle}")
    expect(guideSource).toContain("value={postSummary}")
    expect(guideSource).toContain("value={postVisibility}")
    expect(guideSource).toContain("{postTags.map((tag) => (")
    expect(guideSource).toContain("const handleTagDraftChange = (nextValue: string) =>")
    expect(guideSource).toContain("const handleTagDraftKeyDown: KeyboardEventHandler<HTMLInputElement>")
    expect(guideSource).toContain("<EditorInspectorTagInputRow>")
    expect(guideSource).not.toContain("onRecommend")
    expect(guideSource).not.toContain("isRecommend")
    expect(guideSource).toContain("placeholder=\"태그 추가\"")
    expect(guideSource).toContain("<strong>{postTitle.trim() || \"제목을 입력하세요\"}</strong>")
    expect(guideSource).toContain("<span>{primaryTag} · {readTimeText}</span>")
    expect(guideSource).not.toContain("캐시가 빨라질수록 더 중요해지는 무효화 전략")
    expect(guideSource).not.toContain("ETag, Redis, CDN surrogate key")
    expect(guideSource).not.toContain("2026.06.19")
    expect(guideSource).not.toContain("2.1K")
    expect(guideSource).toContain("const countMarkdownLinkWarnings = (markdown: string)")
    expect(guideSource).toContain("return !href || /^https?:\\/\\/$/.test(href)")
    expect(guideSource).toContain("const linkWarningCount = countMarkdownLinkWarnings(postContent)")
    expect(guideSource).toContain("<strong>링크 검사</strong>")
    expect(guideSource).toContain('linkWarningCount === 0 ? "PASS" : `${linkWarningCount} WARN`')
    expect(guideSource).not.toContain("<strong>요약</strong>")
    expect(guideSource).not.toContain("ETag, Redis, CDN")
    expect(guideSource).not.toContain("ETAG")
    expect(guideSource).not.toContain("INVALIDATION")
    expect(editorRootStyle).toContain("height: 100vh;")
    expect(editorRootStyle).toContain("height: 100dvh;")
    expect(editorRootStyle).toContain("min-height: 100dvh;")
    expect(editorRootStyle).toContain("grid-template-rows: 58px minmax(0, 1fr);")
    expect(editorRootStyle).toContain("overflow: hidden;")
    expect(editorRootStyle).toContain("theme.publicDesign.readableSurface")
    expect(editorRootStyle).not.toContain("grid-template-rows: auto 1fr;")
    expect(editorPartsSource).toContain("height: 58px;")
    expect(editorPartsSource).toContain("min-height: 58px;")
    expect(editorPartsSource).toContain("grid-template-columns: 240px minmax(0, 1fr) auto;")
    expect(editorPartsSource).toContain("gap: 20px;")
    expect(editorPartsSource).toContain("padding: 0 16px;")
    expect(editorFrameStyle).toContain("min-height: 0;")
    expect(editorFrameStyle).toContain("width: 100vw;")
    expect(editorFrameStyle).toContain("max-width: 100vw;")
    expect(editorFrameStyle).toContain("overflow-x: hidden;")
    expect(editorFrameStyle).toContain("overflow-y: auto;")
    expect(editorPartsSource).toContain("padding: 20px 14px;")
    expect(editorPartsSource).toContain("font: 750 11px/1 ui-monospace")
    expect(editorPartsSource).toContain("letter-spacing: 0.08em;")
    expect(editorPartsSource).toContain("display: flex;")
    expect(editorPartsSource).toContain("gap: 9px;")
    expect(editorPartsSource).toContain("padding: 8px 6px;")
    expect(editorPartsSource).toContain("padding-left: 20px;")
    expect(editorPartsSource).toContain("padding-left: 34px;")
    expect(editorPartsSource).toContain("grid-template-columns: 220px minmax(0, 1fr) 300px;")
    expect(editorMetaSectionStyle).toContain("gap: 0;")
    expect(editorMetaSectionStyle).toContain("border-bottom: 1px solid")
    expect(editorMetaSectionStyle).toContain("theme.publicDesign.readableSurface")
    expect(editorMetaSectionStyle).toContain("width: 100vw;")
    expect(editorMetaSectionStyle).toContain("max-width: 100vw;")
    expect(editorMetaSectionStyle).toContain("box-sizing: border-box;")
    expect(titleInputStyle).toContain("max-width: 100%;")
    expect(editorTagRowStyle).toContain("gap: 7px;")
    expect(editorTagRowStyle).toContain("min-height: 26px;")
    expect(selectedTagChipStyle).toContain("min-height: 26px;")
    expect(selectedTagChipStyle).toContain("background: transparent;")
    expect(selectedTagChipStyle).toContain("font: 650 11px/1 ui-monospace")
    expect(selectedTagChipStyle).not.toContain("transform 0.18s ease")
    expect(selectedTagChipStyle).not.toContain("transform: none;")
    expect(editorHeaderMetaRowStyle).toContain("gap: 9px;")
    expect(editorHeaderMetaRowStyle).toContain("margin-top: 10px;")
    expect(editorHeaderMetaRowStyle).not.toContain("justify-content: space-between;")
    expect(editorWritingColumnStyle).toContain("position: relative;")
    expect(editorWritingColumnStyle).toContain("grid-template-rows: auto minmax(0, 1fr);")
    expect(editorWritingColumnStyle).toContain("overflow: hidden;")
    expect(editorCanvasSectionStyle).toContain("overflow: hidden;")
    expect(editorCanvasSectionStyle).toContain("border: 0;")
    expect(editorCanvasSectionStyle).toContain("width: 100vw;")
    expect(editorCanvasSectionStyle).toContain("max-width: 100vw;")
    expect(editorCanvasSectionStyle).toContain("box-sizing: border-box;")
    expect(editorCanvasSectionStyle).not.toContain("border: 1px solid")
    expect(publishNoticeStyle).toContain("position: absolute;")
    expect(publishNoticeStyle).toContain("bottom: 18px;")
    expect(publishNoticeStyle).toContain("border-radius: 6px;")
    expect(publishNoticeStyle).not.toContain("border-radius: 10px;")
    expect(editorPartsSource).toContain("padding: 22px 28px 17px;")
    expect(editorPartsSource).toContain("height: 112px;")
    expect(editorPartsSource).toContain("padding: 14px;")
    expect(editorPartsSource).toContain("color: #88a9e8;")
    expect(editorPartsSource).toContain("font: 700 13px/1.4 ui-monospace")
    expect(editorPartsSource).toContain("padding: 12px 12px 0;")
    expect(editorPartsSource).toContain("line-height: 1.4;")
    expect(editorPartsSource).toContain("padding: 6px 12px 12px;")
    expect(editorPartsSource).toContain("font-size: 11px;")
    expect(editorPartsSource).toContain("@media (max-width: 1100px)")
    expect(editorPartsSource).toContain("grid-template-columns: 190px minmax(0, 1fr);")
    expect(editorPartsSource).toContain("grid-template-rows: minmax(0, 1fr) auto;")
    expect(editorPartsSource).toContain("@media (max-width: 820px)")
    expect(editorPartsSource).toContain("z-index: 200;")
    expect(editorPartsSource).toContain("background: rgba(10, 12, 16, 0.42);")
    expect(editorPartsSource).toContain("width: min(100%, 590px);")
    expect(editorPartsSource).toContain("height: 64px;")
    expect(editorInspectorStyle).toContain("font: 750 11px/1 ui-monospace")
    expect(editorInspectorStyle).toContain("font: 700 10px/1 ui-monospace")
    expect(editorInspectorStyle).toContain("margin: 0 0 8px;")
    expect(editorInspectorStyle).toContain("grid-column: 1 / -1;")
    expect(editorInspectorStyle).toContain("max-height: min(38vh, 360px);")
    expect(editorInspectorStyle).not.toContain("display: none;")
    expect(inspectorTagInputRowStyle).toContain("display: flex;")
    expect(inspectorTagInputRowStyle).toContain("gap: 6px;")
    expect(inspectorTagInputRowStyle).toContain("min-width: 0;")
    expect(inspectorTagInputRowStyle).toContain("width: 38px;")
    expect(inspectorFullWidthActionStyle).toContain("width: 100%;")
    expect(inspectorFullWidthActionStyle).toContain("margin-top: 8px;")
    expect(guideSource).toContain("### 제목 3")
    expect(guideSource).toContain("- [ ] 예정")
    expect(guideSource).toContain('```kotlin title=\\"invalidatePost.kt\\"')
    expect(guideSource).toContain("CONFIG.projects?.[0]")
    expect(guideSource).toContain("프로젝트 리포지터리")
  })

  test("V4 상세 헤더는 reference 샘플 대신 backend post 데이터를 사용한다", () => {
    const headerSource = readFileSync(path.resolve(__dirname, "../src/routes/Detail/PostDetail/PostHeader.tsx"), "utf8")
    const headerStyleSource = readFileSync(path.resolve(__dirname, "../src/routes/Detail/PostDetail/PostHeader.styles.ts"), "utf8")
    const mapperSource = readFileSync(path.resolve(__dirname, "../src/apis/backend/posts/PostApiMappers.ts"), "utf8")
    const metadataSource = readFileSync(
      path.resolve(__dirname, "../src/routes/Detail/PostDetail/postDetailMetadataModel.ts"),
      "utf8"
    )

    expect(mapperSource).toContain('name: post.authorName || post.authorUsername || "익명"')
    expect(headerSource).toContain("<h1 className=\"title\">{data.title}</h1>")
    expect(headerSource).toContain('alt={`${authorName} profile image`}')
    expect(headerSource).toContain("width={38}")
    expect(headerSource).toContain("height={38}")
    expect(headerStyleSource).toContain("width: min(100%, 880px);")
    expect(headerStyleSource).toContain("margin: 0 auto;")
    expect(headerStyleSource).toContain("padding: 0;")
    expect(headerStyleSource).not.toContain(".taxonomyRow")
    expect(headerStyleSource).not.toContain(".staticTag")
    expect(headerStyleSource).toContain("gap: 20px;")
    expect(headerStyleSource).toContain("gap: 11px;")
    expect(headerStyleSource).toContain("letter-spacing: -0.065em;")
    expect(headerStyleSource).not.toContain("max-width: 14ch;")
    expect(headerStyleSource).not.toContain("@media (max-width: 768px)")
    expect(headerStyleSource).toContain("@media (max-width: 820px)")
    expect(headerStyleSource).toContain("gap: 12px 22px;")
    expect(headerStyleSource).toContain("font-size: 12px;")
    expect(headerStyleSource).toContain("line-height: 1.4;")
    expect(headerStyleSource).toContain("min-height: auto;")
    expect(headerStyleSource).toContain("border: 0;")
    expect(headerStyleSource).toContain("width: 38px;")
    expect(headerStyleSource).toContain("height: 38px;")
    expect(headerStyleSource).not.toContain("width: 48px;")
    expect(headerStyleSource).not.toContain("height: 48px;")
    expect(headerStyleSource).not.toContain("border-bottom: 1px solid #dfe1e5;")
    expect(headerSource).toContain("const postAuthor = data.author?.find((author) => author.name?.trim()) ?? null")
    expect(headerSource).toContain('postAuthor?.name?.trim() || adminProfile?.nickname?.trim() || adminProfile?.name?.trim() || "익명"')
    expect(headerSource).toContain("const authorImageSrc = usingAdminFallback")
    expect(headerSource).toContain("const authorRole = usingAdminFallback")
    expect(headerSource).toContain("adminProfile?.profileImageDirectUrl")
    expect(headerSource).toContain("adminProfile?.profileImageUrl")
    expect(headerSource).toContain('const primaryTaxonomy = (data.category?.[0] || tags[0] || "").trim()')
    expect(headerSource).toContain("const heroLabels = primaryTaxonomy ? [primaryTaxonomy, typeLabel] : [typeLabel]")
    expect(headerSource).not.toContain("CONFIG.profile.image")
    expect(headerSource).toContain('<span className="avatarFallback" aria-hidden="true" />')
    expect(headerStyleSource).toContain(".avatarFallback")
    expect(headerStyleSource).toContain(".avatarFallback::before")
    expect(headerStyleSource).toContain(".avatarFallback::after")
    expect(headerSource).toContain("{authorName && (")
    expect(headerSource).toContain("<strong>{authorName}</strong>")
    expect(headerSource).toContain("useRootAdminProfile")
    expect(headerSource).toContain("const adminProfile = useRootAdminProfile()")
    expect(headerSource).toContain("const authorRole = usingAdminFallback ? adminProfile?.profileRole?.trim() || \"\" : \"\"")
    expect(headerSource).not.toContain("CONFIG.profile.role ? <div className=\"metaText\">")
    expect(metadataSource).toContain('post.author?.find((author) => author.name.trim().length > 0)?.name.trim() ||\n  "익명"')
    expect(metadataSource).not.toContain("CONFIG.profile.name")
    expect(headerSource).toContain("const readTimeText =")
    expect(headerSource).toContain("data.content || data.summary || data.title")
    expect(headerSource).toContain("const viewText =")
    expect(headerSource).toContain("Intl.NumberFormat(CONFIG.lang).format(viewCount)")
    expect(headerSource).toContain("<span className=\"statChip\">{publishedAt}</span>")
    expect(headerSource).toContain("<span className=\"statChip\">{readTimeText}</span>")
    expect(headerSource).toContain("<span className=\"statChip\">{viewText}</span>")
    expect(headerSource).toContain("UPDATED {modifiedAt}")
    expect(headerSource).not.toContain("댓글 {data.commentsCount ?? 0}")
    expect(headerSource).toContain("{likesCount ?? data.likesCount ?? 0}")
    expect(headerSource).not.toContain("캐시가 빨라질수록")
    expect(headerSource).not.toContain("ETag")
    expect(headerSource).not.toContain("2.1K")
    expect(headerSource).not.toContain("11분")
  })

  test("canonical detail static props는 ISR 생성 실패 시 recovery shell로 폴백한다", () => {
    const source = readFileSync(path.resolve(__dirname, "../src/libs/server/postDetailPage.ts"), "utf8")

    expect(source).toContain("export const buildCanonicalPostDetailStaticProps = async (")
    expect(source).toContain("postDetail = await getPostDetailById(postId)")
    expect(source).toContain("const shouldServeClientRecoveryShell = shouldClientRecover || (IS_QA_STATIC_RECOVERY_MODE && !postDetail)")
    expect(source).toContain("if (!postDetail && !shouldServeClientRecoveryShell) return { notFound: true }")
    expect(source).toContain("revalidate:")
    expect(source).toContain('shouldServeClientRecoveryShell || initialAdminProfileSource === "static-fallback"')
    expect(source).toContain("? DETAIL_RECOVERY_REVALIDATE_SECONDS")
    expect(source).toContain(": DETAIL_ISR_REVALIDATE_SECONDS,")
  })
})
